{
    "affected": [
        {
            "package": {
                "ecosystem": "photon:1.0",
                "name": "gettext",
                "purl": "pkg:rpm/vmware/gettext?distro=photon-1"
            }
        },
        {
            "package": {
                "ecosystem": "photon:1.0",
                "name": "python3",
                "purl": "pkg:rpm/vmware/python3?distro=photon-1"
            }
        },
        {
            "package": {
                "ecosystem": "photon:1.0",
                "name": "curl",
                "purl": "pkg:rpm/vmware/curl?distro=photon-1"
            }
        },
        {
            "package": {
                "ecosystem": "photon:1.0",
                "name": "libarchive",
                "purl": "pkg:rpm/vmware/libarchive?distro=photon-1"
            }
        },
        {
            "package": {
                "ecosystem": "photon:1.0",
                "name": "python2",
                "purl": "pkg:rpm/vmware/python2?distro=photon-1"
            }
        }
    ],
    "id": "PHSA-2019-0216",
    "modified": "2023-03-16T05:25:30Z",
    "published": "2019-03-15T00:00:00Z",
    "references": [
        {
            "type": "ADVISORY",
            "url": "https://github.com/vmware/photon/wiki/Security-Update-1.0-216"
        }
    ],
    "related": [
        "CVE-2019-9636",
        "CVE-2018-16890",
        "CVE-2018-1000878",
        "CVE-2018-18751",
        "CVE-2018-1000877"
    ]
}