{
    "affected": [
        {
            "package": {
                "ecosystem": "photon:1.0",
                "name": "python-py",
                "purl": "pkg:rpm/vmware/python-py?distro=photon-1"
            },
            "ranges": {
                "events": [
                    {
                        "introduced": "0"
                    },
                    {
                        "fixed": "1.4.33-2.ph1"
                    }
                ],
                "type": "ECOSYSTEM"
            }
        },
        {
            "package": {
                "ecosystem": "Photon OS:1.0",
                "name": "python-py",
                "purl": "pkg:rpm/vmware/python-py?distro=photon-1"
            },
            "ranges": {
                "events": [
                    {
                        "introduced": "0"
                    },
                    {
                        "fixed": "1.4.33-2.ph1"
                    }
                ],
                "type": "ECOSYSTEM"
            }
        }
    ],
    "id": "PHSA-2021-0419",
    "modified": "2023-05-07T05:25:00Z",
    "published": "2021-07-27T00:00:00Z",
    "references": [
        {
            "type": "ADVISORY",
            "url": "https://github.com/vmware/photon/wiki/Security-Update-1.0-419"
        }
    ],
    "related": [
        "CVE-2020-29651"
    ]
}