{
    "affected": [
        {
            "package": {
                "ecosystem": "Photon OS:3.0",
                "name": "python-py",
                "purl": "pkg:rpm/vmware/python-py?distro=photon-3"
            },
            "ranges": {
                "events": [
                    {
                        "introduced": "0"
                    },
                    {
                        "fixed": "1.6.0-2.ph3"
                    }
                ],
                "type": "ECOSYSTEM"
            }
        },
        {
            "package": {
                "ecosystem": "Photon OS:3.0",
                "name": "python-py",
                "purl": "pkg:rpm/vmware/python-py?distro=photon-3"
            },
            "ranges": [
                {
                    "events": [
                        {
                            "introduced": "0"
                        },
                        {
                            "fixed": "1.6.0-2.ph3"
                        }
                    ],
                    "type": "ECOSYSTEM"
                }
            ]
        }
    ],
    "id": "PHSA-2021-3.0-0258",
    "modified": "2025-01-24T05:27:06Z",
    "published": "2021-06-24T00:00:00Z",
    "references": [
        {
            "type": "ADVISORY",
            "url": "https://github.com/vmware/photon/wiki/Security-Update-3.0-258"
        }
    ],
    "related": [
        "CVE-2020-29651"
    ]
}