{
    "affected": [
        {
            "package": {
                "ecosystem": "Photon OS:3.0",
                "name": "python3",
                "purl": "pkg:rpm/vmware/python3?distro=photon-3"
            }
        },
        {
            "package": {
                "ecosystem": "Photon OS:3.0",
                "name": "python2",
                "purl": "pkg:rpm/vmware/python2?distro=photon-3"
            },
            "ranges": {
                "events": [
                    {
                        "introduced": "0"
                    },
                    {
                        "fixed": "2.7.17-7.ph3"
                    }
                ],
                "type": "ECOSYSTEM"
            }
        },
        {
            "package": {
                "ecosystem": "Photon OS:3.0",
                "name": "python2",
                "purl": "pkg:rpm/vmware/python2?distro=photon-3"
            },
            "ranges": [
                {
                    "events": [
                        {
                            "introduced": "0"
                        },
                        {
                            "fixed": "2.7.17-7.ph3"
                        }
                    ],
                    "type": "ECOSYSTEM"
                }
            ]
        }
    ],
    "id": "PHSA-2022-3.0-0463",
    "modified": "2025-01-24T05:27:06Z",
    "published": "2022-10-05T00:00:00Z",
    "references": [
        {
            "type": "ADVISORY",
            "url": "https://github.com/vmware/photon/wiki/Security-Update-3.0-463"
        }
    ],
    "related": [
        "CVE-2021-4189",
        "CVE-2015-20107"
    ]
}